services:
  database:
    # TODO: add healthcheck
    ports:
      - "27017:27017"
    image: mongo:6
    restart: unless-stopped
    user: "mongodb:mongodb"
    volumes:
      - ./mongodata:/data:Z
      - ./dump:/dump:Z